// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    [Migration("20240811195346_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d9413f5-991c-4bcd-91af-07322207e098"),
                            Date = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete online courses and build projects to learn ASP.NET Core.",
                            ImagePath = "learn_aspnet_core.jpg",
                            Progress = 0.0,
                            Title = "Learn ASP.NET Core",
                            UserId = new Guid("a91f61ca-a16b-45c1-a3ec-67cb720c805f")
                        },
                        new
                        {
                            Id = new Guid("bad0900a-ed96-4bad-880a-cc3cff0e0353"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read a variety of books across different genres.",
                            ImagePath = "read_books.jpg",
                            Progress = 0.0,
                            Title = "Read 20 Books",
                            UserId = new Guid("ef74ae7d-0e13-479f-95a0-cc2e637f184e")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("GoalId");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe10bc5c-a2ed-40b0-bcfe-1302ef7aef7f"),
                            Date = new DateTime(2024, 9, 10, 14, 53, 45, 113, DateTimeKind.Local).AddTicks(1021),
                            Description = "Finish the first online course.",
                            GoalId = new Guid("5d9413f5-991c-4bcd-91af-07322207e098"),
                            Status = "Pending",
                            Title = "Complete Course 1"
                        },
                        new
                        {
                            Id = new Guid("b6093973-ce0d-4887-ad13-b8d30aebbcf0"),
                            Date = new DateTime(2024, 10, 10, 14, 53, 45, 113, DateTimeKind.Local).AddTicks(1095),
                            Description = "Finish the second online course.",
                            GoalId = new Guid("bad0900a-ed96-4bad-880a-cc3cff0e0353"),
                            Status = "Pending",
                            Title = "Complete Course 2"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d511083-0905-408b-8a07-dcf886bb82ac"),
                            Description = "Personal"
                        },
                        new
                        {
                            Id = new Guid("e78f3eb8-555d-42ca-bf98-838bd97ffb49"),
                            Description = "Professional"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d81a2cf-55d0-4cf7-9f95-0d5a13d591e3"),
                            Date = new DateTime(2024, 8, 18, 14, 53, 45, 113, DateTimeKind.Local).AddTicks(6792),
                            Description = "Read and complete exercises in Chapter 1 of the textbook.",
                            MilestoneId = new Guid("fe10bc5c-a2ed-40b0-bcfe-1302ef7aef7f"),
                            TagId = new Guid("9d511083-0905-408b-8a07-dcf886bb82ac"),
                            Title = "Complete Chapter 1",
                            UserId = new Guid("a91f61ca-a16b-45c1-a3ec-67cb720c805f")
                        },
                        new
                        {
                            Id = new Guid("dba365d2-4e15-4180-965b-996f4cf6d144"),
                            Date = new DateTime(2024, 8, 25, 14, 53, 45, 113, DateTimeKind.Local).AddTicks(6928),
                            Description = "Write a review of the latest book read.",
                            MilestoneId = new Guid("b6093973-ce0d-4887-ad13-b8d30aebbcf0"),
                            TagId = new Guid("e78f3eb8-555d-42ca-bf98-838bd97ffb49"),
                            Title = "Write Book Review",
                            UserId = new Guid("ef74ae7d-0e13-479f-95a0-cc2e637f184e")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a91f61ca-a16b-45c1-a3ec-67cb720c805f"),
                            Email = "smarin@sample.com",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        },
                        new
                        {
                            Id = new Guid("ef74ae7d-0e13-479f-95a0-cc2e637f184e"),
                            Email = "Gerald@sample.com",
                            FirstName = "Gerald",
                            LastName = "Vallejos",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("tblMilestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("tblTasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("tblTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.Navigation("Milestone");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("tblMilestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblGoals");

                    b.Navigation("tblTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
