// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    [Migration("20250103192459_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblBoard_Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("tblBoard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("acf38b32-9583-4f95-a637-8a13db7dfe7e"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(8968),
                            Description = "Main project board",
                            Name = "Main Board",
                            ProjectId = new Guid("75a1a40a-5a9f-4352-8272-ad0e63ed7ab8")
                        },
                        new
                        {
                            Id = new Guid("1bd3802b-69cf-4af2-a98e-8cc1c0be373d"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(8969),
                            Description = "Sprint planning board",
                            Name = "Sprint Board",
                            ProjectId = new Guid("3df57df9-d100-47f9-9ae4-4e105f12e712")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("WIPLimit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblColumn_Id");

                    b.HasIndex("BoardId", "Order");

                    b.ToTable("tblColumn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f51342-eb10-4b6f-bb42-e9a726cc3ea3"),
                            BoardId = new Guid("acf38b32-9583-4f95-a637-8a13db7dfe7e"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9031),
                            Name = "To Do",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("4d03991b-fa58-4a96-b080-5b6e05ec7d21"),
                            BoardId = new Guid("acf38b32-9583-4f95-a637-8a13db7dfe7e"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9032),
                            Name = "In Progress",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("2793736b-faef-46df-b6f6-a02c59a725b1"),
                            BoardId = new Guid("acf38b32-9583-4f95-a637-8a13db7dfe7e"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9033),
                            Name = "Done",
                            Order = 3
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("ProjectId", "DueDate");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13c60603-ea4a-4421-ac63-3ea3bc7a8c65"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9004),
                            Description = "First quarter objectives",
                            DueDate = new DateTime(2025, 4, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(8997),
                            Progress = 0.0,
                            ProjectId = new Guid("75a1a40a-5a9f-4352-8272-ad0e63ed7ab8"),
                            Title = "Q1 Goals"
                        },
                        new
                        {
                            Id = new Guid("e00f02fa-ab86-46dc-8d28-f05bdc4c9845"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9006),
                            Description = "Second quarter objectives",
                            DueDate = new DateTime(2025, 7, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9005),
                            Progress = 0.0,
                            ProjectId = new Guid("3df57df9-d100-47f9-9ae4-4e105f12e712"),
                            Title = "Q2 Goals"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MilestoneStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("MilestoneStatusId");

                    b.HasIndex("GoalId", "DueDate");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a5b501e-b53c-4027-8351-923cc5cb6875"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9056),
                            Description = "First sprint milestone",
                            DueDate = new DateTime(2025, 2, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9055),
                            GoalId = new Guid("13c60603-ea4a-4421-ac63-3ea3bc7a8c65"),
                            MilestoneStatusId = new Guid("019cd1a7-0156-4970-bf7b-5f400ff5a143"),
                            Title = "Sprint 1"
                        },
                        new
                        {
                            Id = new Guid("526fcb90-921f-465c-a2a5-25c08965cb04"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9059),
                            Description = "Second sprint milestone",
                            DueDate = new DateTime(2025, 3, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9058),
                            GoalId = new Guid("13c60603-ea4a-4421-ac63-3ea3bc7a8c65"),
                            MilestoneStatusId = new Guid("019cd1a7-0156-4970-bf7b-5f400ff5a143"),
                            Title = "Sprint 2"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestoneStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestoneStatus_Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblMilestoneStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019cd1a7-0156-4970-bf7b-5f400ff5a143"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone not started",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Not Started"
                        },
                        new
                        {
                            Id = new Guid("ef1634ea-b4ed-455e-a015-b63e6058f678"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone in progress",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("cadf4f1d-15da-446d-8de7-9763f84529b2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone completed",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblPriority_Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblPriority", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e1822f2-99a3-4d16-9186-13a2eef774a4"),
                            ColorCode = "#00FF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Low priority",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Low"
                        },
                        new
                        {
                            Id = new Guid("9a74695a-bfd1-46bf-b6d0-99c40650bc6e"),
                            ColorCode = "#FFFF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medium priority",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("0a67b914-5e01-4e66-bb59-6d27f95ef957"),
                            ColorCode = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High priority",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblProject_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblProject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("75a1a40a-5a9f-4352-8272-ad0e63ed7ab8"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(8940),
                            Description = "First project",
                            Name = "Project Alpha",
                            UserId = new Guid("6fc8385a-4782-4cd0-9162-1c14e29880d0")
                        },
                        new
                        {
                            Id = new Guid("3df57df9-d100-47f9-9ae4-4e105f12e712"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(8942),
                            Description = "Second project",
                            Name = "Project Beta",
                            UserId = new Guid("dd6e3868-2ded-4ef5-b56f-9224f6ebda75")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc7ca0d7-8bb4-4ef3-8a74-5b6e677f9c87"),
                            Color = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bug"
                        },
                        new
                        {
                            Id = new Guid("9f5baf7c-4283-4ae2-81d6-028176c013f4"),
                            Color = "#00FF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Feature"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TagId");

                    b.HasIndex("ColumnId", "Order");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("03443b40-0a1f-4a8f-ad45-c19e73d5bfad"),
                            AssigneeId = new Guid("6fc8385a-4782-4cd0-9162-1c14e29880d0"),
                            ColumnId = new Guid("a3f51342-eb10-4b6f-bb42-e9a726cc3ea3"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9086),
                            Description = "Set up project infrastructure",
                            DueDate = new DateTime(2025, 1, 10, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9082),
                            MilestoneId = new Guid("2a5b501e-b53c-4027-8351-923cc5cb6875"),
                            ModifiedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9086),
                            Order = 1,
                            PriorityId = new Guid("9a74695a-bfd1-46bf-b6d0-99c40650bc6e"),
                            TagId = new Guid("9f5baf7c-4283-4ae2-81d6-028176c013f4"),
                            Title = "Initial Setup"
                        },
                        new
                        {
                            Id = new Guid("de4a3ca1-07b1-4b38-9751-ffa2363b8bd3"),
                            AssigneeId = new Guid("dd6e3868-2ded-4ef5-b56f-9224f6ebda75"),
                            ColumnId = new Guid("4d03991b-fa58-4a96-b080-5b6e05ec7d21"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9091),
                            Description = "Resolve authentication issues",
                            DueDate = new DateTime(2025, 1, 6, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9091),
                            MilestoneId = new Guid("2a5b501e-b53c-4027-8351-923cc5cb6875"),
                            ModifiedAt = new DateTime(2025, 1, 3, 19, 24, 58, 475, DateTimeKind.Utc).AddTicks(9092),
                            Order = 1,
                            PriorityId = new Guid("0a67b914-5e01-4e66-bb59-6d27f95ef957"),
                            TagId = new Guid("dc7ca0d7-8bb4-4ef3-8a74-5b6e677f9c87"),
                            Title = "Fix Login Bug"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fc8385a-4782-4cd0-9162-1c14e29880d0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "75K3eLr+dx6JJFuJ7LwIpEpOFmwGZZkRiB84PURz6U8="
                        },
                        new
                        {
                            Id = new Guid("dd6e3868-2ded-4ef5-b56f-9224f6ebda75"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "75K3eLr+dx6JJFuJ7LwIpEpOFmwGZZkRiB84PURz6U8="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBoard_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblBoard", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblColumn_tblBoard");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("Goals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.HasOne("AimHigh.PL.Entities.tblMilestoneStatus", "MilestoneStatus")
                        .WithMany("Milestones")
                        .HasForeignKey("MilestoneStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblMilestoneStatus");

                    b.Navigation("Goal");

                    b.Navigation("MilestoneStatus");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblProject_tblUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "Assignee")
                        .WithMany("Tasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.HasOne("AimHigh.PL.Entities.tblColumn", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblColumn");

                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("Tasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblPriority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_tblTask_tblPriority");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("Tasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblTag");

                    b.Navigation("Assignee");

                    b.Navigation("Column");

                    b.Navigation("Milestone");

                    b.Navigation("Priority");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestoneStatus", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblPriority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
