// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    [Migration("20250103080205_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblBoard_Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("tblBoard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e48adb57-e598-4eb8-b42f-5a82de8a1f55"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8276),
                            Description = "Track development progress",
                            Name = "Development Tasks",
                            ProjectId = new Guid("57ff96d0-2815-40e1-b74d-c9a41ac539f4")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("WIPLimit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblColumn_Id");

                    b.HasIndex("BoardId", "Order");

                    b.ToTable("tblColumn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("708404f5-c420-4abe-baa6-b8e7aca4e2d5"),
                            BoardId = new Guid("e48adb57-e598-4eb8-b42f-5a82de8a1f55"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8296),
                            Name = "To Do",
                            Order = 1,
                            WIPLimit = 5
                        },
                        new
                        {
                            Id = new Guid("37ca78cb-fa3a-45e6-b9ac-f16ca457c709"),
                            BoardId = new Guid("e48adb57-e598-4eb8-b42f-5a82de8a1f55"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8299),
                            Name = "In Progress",
                            Order = 2,
                            WIPLimit = 3
                        },
                        new
                        {
                            Id = new Guid("0a6c8c66-346f-4028-8779-4ba7ce03e960"),
                            BoardId = new Guid("e48adb57-e598-4eb8-b42f-5a82de8a1f55"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8300),
                            Name = "Done",
                            Order = 3
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("ProjectId", "DueDate");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c916a43-bdf2-46df-b26b-fafbd5da960a"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8327),
                            Description = "Complete and launch the new company website",
                            DueDate = new DateTime(2025, 4, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8321),
                            Progress = 0.0,
                            ProjectId = new Guid("57ff96d0-2815-40e1-b74d-c9a41ac539f4"),
                            Title = "Launch New Website"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("GoalId", "DueDate");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1dcd39f-4bec-4067-a7ec-1ecd0ea5205e"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8345),
                            Description = "Complete all frontend components",
                            DueDate = new DateTime(2025, 2, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8344),
                            GoalId = new Guid("0c916a43-bdf2-46df-b26b-fafbd5da960a"),
                            Status = "NotStarted",
                            Title = "Frontend Development"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblProject_Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("tblProject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("57ff96d0-2815-40e1-b74d-c9a41ac539f4"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8250),
                            Description = "Complete overhaul of company website",
                            Name = "Website Redesign",
                            OwnerId = new Guid("90cce612-3658-4219-af21-ab5f41eedaed")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f21663ae-7a28-4b4e-901a-dbe7b881e7ed"),
                            Color = "#FF5733",
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8362),
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("27f382d2-4ab0-479e-a8cf-e473ef454c01"),
                            Color = "#C70039",
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8364),
                            Name = "High Priority"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("TagId");

                    b.HasIndex("ColumnId", "Order");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f26285bc-d717-4fd7-85f5-a1da6b384ce8"),
                            AssigneeId = new Guid("90cce612-3658-4219-af21-ab5f41eedaed"),
                            ColumnId = new Guid("708404f5-c420-4abe-baa6-b8e7aca4e2d5"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8389),
                            Description = "Create responsive design for homepage",
                            DueDate = new DateTime(2025, 1, 10, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8385),
                            MilestoneId = new Guid("c1dcd39f-4bec-4067-a7ec-1ecd0ea5205e"),
                            Order = 1,
                            Priority = "High",
                            TagId = new Guid("f21663ae-7a28-4b4e-901a-dbe7b881e7ed"),
                            Title = "Design Homepage"
                        },
                        new
                        {
                            Id = new Guid("886a9190-dd9d-4aad-be36-fd7452c3b693"),
                            AssigneeId = new Guid("90cce612-3658-4219-af21-ab5f41eedaed"),
                            ColumnId = new Guid("708404f5-c420-4abe-baa6-b8e7aca4e2d5"),
                            CreatedAt = new DateTime(2025, 1, 3, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8395),
                            Description = "Implement responsive navigation menu",
                            DueDate = new DateTime(2025, 1, 8, 8, 2, 4, 725, DateTimeKind.Utc).AddTicks(8394),
                            MilestoneId = new Guid("c1dcd39f-4bec-4067-a7ec-1ecd0ea5205e"),
                            Order = 2,
                            Priority = "Medium",
                            TagId = new Guid("27f382d2-4ab0-479e-a8cf-e473ef454c01"),
                            Title = "Setup Navigation"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90cce612-3658-4219-af21-ab5f41eedaed"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "Ov7tBO7KAvNiYFcbGd6wiYrfq889AoOqzcnK+4HgsOE="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("tblBoards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBoard_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblBoard", "Board")
                        .WithMany("tblColumns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblColumn_tblBoard");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("tblGoals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("tblMilestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblProject_tblUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "Assignee")
                        .WithMany("Tasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.HasOne("AimHigh.PL.Entities.tblColumn", "Column")
                        .WithMany("tblTasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblColumn");

                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("tblTasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("tblTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblTag");

                    b.Navigation("Assignee");

                    b.Navigation("Column");

                    b.Navigation("Milestone");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Navigation("tblColumns");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("tblMilestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Navigation("tblBoards");

                    b.Navigation("tblGoals");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
