// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    [Migration("20250102032240_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1988cf4b-3c3d-45f3-8b97-62a3c1991303"),
                            Date = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete online courses and build projects to learn ASP.NET Core.",
                            ImagePath = "learn_aspnet_core.jpg",
                            Progress = 0.0,
                            Title = "Learn ASP.NET Core",
                            UserId = new Guid("856145c7-622b-43c1-bc13-97d56d40562f")
                        },
                        new
                        {
                            Id = new Guid("8ba08888-0e2d-4125-b63f-3766317274ff"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read a variety of books across different genres.",
                            ImagePath = "read_books.jpg",
                            Progress = 0.0,
                            Title = "Read 20 Books",
                            UserId = new Guid("79a2a591-4fa0-4e64-9c0c-d0b61b52eef3")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("GoalId");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dc09fe8-5929-43c9-a038-dbd1e09e8604"),
                            Date = new DateTime(2025, 1, 31, 21, 22, 39, 544, DateTimeKind.Local).AddTicks(5660),
                            Description = "Finish the first online course.",
                            GoalId = new Guid("1988cf4b-3c3d-45f3-8b97-62a3c1991303"),
                            Status = "Pending",
                            Title = "Complete Course 1"
                        },
                        new
                        {
                            Id = new Guid("2d01a6cf-513f-46d4-af48-1b7dbb098eed"),
                            Date = new DateTime(2025, 3, 2, 21, 22, 39, 544, DateTimeKind.Local).AddTicks(5729),
                            Description = "Finish the second online course.",
                            GoalId = new Guid("8ba08888-0e2d-4125-b63f-3766317274ff"),
                            Status = "Pending",
                            Title = "Complete Course 2"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblStatus_Id");

                    b.ToTable("tblStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5184c11-1088-4186-8c2e-3e8bb7766769"),
                            Order = 1,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("7285d265-779e-4d5b-9238-ce66cfb6c32b"),
                            Order = 2,
                            Title = "Doing"
                        },
                        new
                        {
                            Id = new Guid("99f96284-63a5-4487-947e-ac6dd11abbc6"),
                            Order = 3,
                            Title = "Done"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("36b5f65c-e7e5-4af8-a45b-c8c3eb3aa241"),
                            Description = "Personal"
                        },
                        new
                        {
                            Id = new Guid("3b281150-d8f8-436e-a244-89b62269e1dd"),
                            Description = "Professional"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a727686-5d6a-48b3-9162-57218a3bba64"),
                            Date = new DateTime(2025, 1, 8, 21, 22, 39, 545, DateTimeKind.Local).AddTicks(1424),
                            Description = "Read and complete exercises in Chapter 1 of the textbook.",
                            MilestoneId = new Guid("7dc09fe8-5929-43c9-a038-dbd1e09e8604"),
                            StatusId = new Guid("e5184c11-1088-4186-8c2e-3e8bb7766769"),
                            TagId = new Guid("36b5f65c-e7e5-4af8-a45b-c8c3eb3aa241"),
                            Title = "Complete Chapter 1",
                            UserId = new Guid("856145c7-622b-43c1-bc13-97d56d40562f")
                        },
                        new
                        {
                            Id = new Guid("044d51e3-f802-4ca4-b825-f82dcf690477"),
                            Date = new DateTime(2025, 1, 15, 21, 22, 39, 545, DateTimeKind.Local).AddTicks(1465),
                            Description = "Write a review of the latest book read.",
                            MilestoneId = new Guid("2d01a6cf-513f-46d4-af48-1b7dbb098eed"),
                            StatusId = new Guid("7285d265-779e-4d5b-9238-ce66cfb6c32b"),
                            TagId = new Guid("3b281150-d8f8-436e-a244-89b62269e1dd"),
                            Title = "Write Book Review",
                            UserId = new Guid("79a2a591-4fa0-4e64-9c0c-d0b61b52eef3")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("856145c7-622b-43c1-bc13-97d56d40562f"),
                            Email = "smarin@sample.com",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        },
                        new
                        {
                            Id = new Guid("79a2a591-4fa0-4e64-9c0c-d0b61b52eef3"),
                            Email = "Gerald@sample.com",
                            FirstName = "Gerald",
                            LastName = "Vallejos",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("tblMilestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("tblTasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblStatus", "Status")
                        .WithMany("tblTasks")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblStatus");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("tblTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.Navigation("Milestone");

                    b.Navigation("Status");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("tblMilestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblStatus", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblGoals");

                    b.Navigation("tblTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
