// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    [Migration("20250103190200_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblBoard_Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("tblBoard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee008b61-7d81-4b28-909f-d4026d19708b"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5423),
                            Description = "Main project board",
                            Name = "Main Board",
                            ProjectId = new Guid("95e8a120-65fe-4b35-933f-cb8f8071548d")
                        },
                        new
                        {
                            Id = new Guid("11dca8c5-6bb7-41b1-b5ae-aecffdfd6e81"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5424),
                            Description = "Sprint planning board",
                            Name = "Sprint Board",
                            ProjectId = new Guid("0d349673-ab12-4bf6-a1af-dc2e4b427ac3")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("WIPLimit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblColumn_Id");

                    b.HasIndex("BoardId", "Order");

                    b.ToTable("tblColumn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96fed779-44a0-4b9a-98de-3be19c925416"),
                            BoardId = new Guid("ee008b61-7d81-4b28-909f-d4026d19708b"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5478),
                            Name = "To Do",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("dc94c6fc-1516-4a64-ade3-36bf04a8a7fb"),
                            BoardId = new Guid("ee008b61-7d81-4b28-909f-d4026d19708b"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5479),
                            Name = "In Progress",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("b6d2c9b7-d114-4f9e-8fd0-b763c4537ae6"),
                            BoardId = new Guid("ee008b61-7d81-4b28-909f-d4026d19708b"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5480),
                            Name = "Done",
                            Order = 3
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("ProjectId", "DueDate");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b88d847-3eaf-41da-a0c2-d3365693b021"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5452),
                            Description = "First quarter objectives",
                            DueDate = new DateTime(2025, 4, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5446),
                            Progress = 0.0,
                            ProjectId = new Guid("95e8a120-65fe-4b35-933f-cb8f8071548d"),
                            Title = "Q1 Goals"
                        },
                        new
                        {
                            Id = new Guid("d2e75232-d77b-4b8c-a225-1ed986b3fe5a"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5454),
                            Description = "Second quarter objectives",
                            DueDate = new DateTime(2025, 7, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5453),
                            Progress = 0.0,
                            ProjectId = new Guid("0d349673-ab12-4bf6-a1af-dc2e4b427ac3"),
                            Title = "Q2 Goals"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MilestoneStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("MilestoneStatusId");

                    b.HasIndex("GoalId", "DueDate");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd473337-85bd-4cec-8542-93264ba38679"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5501),
                            Description = "First sprint milestone",
                            DueDate = new DateTime(2025, 2, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5500),
                            GoalId = new Guid("9b88d847-3eaf-41da-a0c2-d3365693b021"),
                            MilestoneStatusId = new Guid("ea9b2fa5-6dff-4d09-a9d1-828a0010e6b0"),
                            Title = "Sprint 1"
                        },
                        new
                        {
                            Id = new Guid("55be96bf-d411-4cac-9ace-96587adddd82"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5503),
                            Description = "Second sprint milestone",
                            DueDate = new DateTime(2025, 3, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5503),
                            GoalId = new Guid("9b88d847-3eaf-41da-a0c2-d3365693b021"),
                            MilestoneStatusId = new Guid("ea9b2fa5-6dff-4d09-a9d1-828a0010e6b0"),
                            Title = "Sprint 2"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestoneStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestoneStatus_Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblMilestoneStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea9b2fa5-6dff-4d09-a9d1-828a0010e6b0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone not started",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Not Started"
                        },
                        new
                        {
                            Id = new Guid("f756a3d6-1b18-44b0-9bb3-f5158569cce1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone in progress",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("b4040d49-4cd0-4c03-84c3-3972eb27eda9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milestone completed",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblPriority_Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblPriority", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df7ffb9e-b58a-4b91-a7d6-587bf8ad0e3e"),
                            ColorCode = "#00FF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Low priority",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Low"
                        },
                        new
                        {
                            Id = new Guid("d0524789-8ba9-4b25-a261-7994bf6455aa"),
                            ColorCode = "#FFFF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medium priority",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("9a23b152-0af2-4ab1-95a8-e861ae304881"),
                            ColorCode = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High priority",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblProject_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblProject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("95e8a120-65fe-4b35-933f-cb8f8071548d"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5395),
                            Description = "First project",
                            Name = "Project Alpha",
                            UserId = new Guid("f6f63289-c9a9-488c-9fd4-264c5ef271b6")
                        },
                        new
                        {
                            Id = new Guid("0d349673-ab12-4bf6-a1af-dc2e4b427ac3"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5397),
                            Description = "Second project",
                            Name = "Project Beta",
                            UserId = new Guid("f7abeec3-99c6-411d-b4cd-d7ae202abf58")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("397379a2-677d-4698-99ab-e7c9981f7855"),
                            Color = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bug"
                        },
                        new
                        {
                            Id = new Guid("97030249-9ade-4950-b911-7b641c785933"),
                            Color = "#00FF00",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Feature"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TagId");

                    b.HasIndex("ColumnId", "Order");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("af0c1ef3-015d-49aa-9b61-c45a58c02e57"),
                            AssigneeId = new Guid("f6f63289-c9a9-488c-9fd4-264c5ef271b6"),
                            ColumnId = new Guid("96fed779-44a0-4b9a-98de-3be19c925416"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5532),
                            Description = "Set up project infrastructure",
                            DueDate = new DateTime(2025, 1, 10, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5528),
                            MilestoneId = new Guid("cd473337-85bd-4cec-8542-93264ba38679"),
                            ModifiedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5532),
                            Order = 1,
                            PriorityId = new Guid("d0524789-8ba9-4b25-a261-7994bf6455aa"),
                            TagId = new Guid("97030249-9ade-4950-b911-7b641c785933"),
                            Title = "Initial Setup"
                        },
                        new
                        {
                            Id = new Guid("7d5a3a4d-56cb-4ea1-b4ad-d5b2c2114249"),
                            AssigneeId = new Guid("f7abeec3-99c6-411d-b4cd-d7ae202abf58"),
                            ColumnId = new Guid("dc94c6fc-1516-4a64-ade3-36bf04a8a7fb"),
                            CreatedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5537),
                            Description = "Resolve authentication issues",
                            DueDate = new DateTime(2025, 1, 6, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5536),
                            MilestoneId = new Guid("cd473337-85bd-4cec-8542-93264ba38679"),
                            ModifiedAt = new DateTime(2025, 1, 3, 19, 1, 59, 318, DateTimeKind.Utc).AddTicks(5537),
                            Order = 1,
                            PriorityId = new Guid("9a23b152-0af2-4ab1-95a8-e861ae304881"),
                            TagId = new Guid("397379a2-677d-4698-99ab-e7c9981f7855"),
                            Title = "Fix Login Bug"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6f63289-c9a9-488c-9fd4-264c5ef271b6"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "75K3eLr+dx6JJFuJ7LwIpEpOFmwGZZkRiB84PURz6U8="
                        },
                        new
                        {
                            Id = new Guid("f7abeec3-99c6-411d-b4cd-d7ae202abf58"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "75K3eLr+dx6JJFuJ7LwIpEpOFmwGZZkRiB84PURz6U8="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBoard_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblBoard", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblColumn_tblBoard");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblProject", "Project")
                        .WithMany("Goals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.HasOne("AimHigh.PL.Entities.tblMilestoneStatus", "MilestoneStatus")
                        .WithMany("Milestones")
                        .HasForeignKey("MilestoneStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblMilestoneStatus");

                    b.Navigation("Goal");

                    b.Navigation("MilestoneStatus");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblProject_tblUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "Assignee")
                        .WithMany("Tasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.HasOne("AimHigh.PL.Entities.tblColumn", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblColumn");

                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("Tasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblPriority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_tblTask_tblPriority");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("Tasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTask_tblTag");

                    b.Navigation("Assignee");

                    b.Navigation("Column");

                    b.Navigation("Milestone");

                    b.Navigation("Priority");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblBoard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblColumn", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestoneStatus", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblPriority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblProject", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
