// <auto-generated />
using System;
using AimHigh.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AimHigh.PL.Migrations
{
    [DbContext(typeof(AimHighEntities))]
    partial class AimHighEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGoal_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e28d0c4-d028-478d-b45a-6f032ae1ac64"),
                            Date = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete online courses and build projects to learn ASP.NET Core.",
                            ImagePath = "learn_aspnet_core.jpg",
                            Progress = 0.0,
                            Title = "Learn ASP.NET Core",
                            UserId = new Guid("ba7c2575-1ff4-4d91-a9db-40c4e37eac96")
                        },
                        new
                        {
                            Id = new Guid("ee7a87ad-d2dc-427b-84f1-02b3e12d25b4"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read a variety of books across different genres.",
                            ImagePath = "read_books.jpg",
                            Progress = 0.0,
                            Title = "Read 20 Books",
                            UserId = new Guid("914d5bdd-1c4c-4d74-b78e-9c26e06ff2e9")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMilestone_Id");

                    b.HasIndex("GoalId");

                    b.ToTable("tblMilestone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b1fd0dd-c5a3-4dff-af65-b18f867ae074"),
                            Date = new DateTime(2024, 8, 20, 15, 31, 4, 531, DateTimeKind.Local).AddTicks(2435),
                            Description = "Finish the first online course.",
                            GoalId = new Guid("6e28d0c4-d028-478d-b45a-6f032ae1ac64"),
                            Status = "Pending",
                            Title = "Complete Course 1"
                        },
                        new
                        {
                            Id = new Guid("cfe1c5c9-8fb7-45e1-b697-c22e8cdb26b0"),
                            Date = new DateTime(2024, 9, 19, 15, 31, 4, 531, DateTimeKind.Local).AddTicks(2497),
                            Description = "Finish the second online course.",
                            GoalId = new Guid("ee7a87ad-d2dc-427b-84f1-02b3e12d25b4"),
                            Status = "Pending",
                            Title = "Complete Course 2"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_tblTag_Id");

                    b.ToTable("tblTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dee65825-5657-498e-b2fd-41bd0650b811"),
                            Description = "Personal"
                        },
                        new
                        {
                            Id = new Guid("0be5e36f-4361-4655-95cf-19a7f1283daf"),
                            Description = "Professional"
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTask_Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("tblTask", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8052fd9c-b3e4-4d04-9ef9-6621eaba5574"),
                            Date = new DateTime(2024, 7, 28, 15, 31, 4, 531, DateTimeKind.Local).AddTicks(5997),
                            Description = "Read and complete exercises in Chapter 1 of the textbook.",
                            MilestoneId = new Guid("2b1fd0dd-c5a3-4dff-af65-b18f867ae074"),
                            TagId = new Guid("dee65825-5657-498e-b2fd-41bd0650b811"),
                            Title = "Complete Chapter 1",
                            UserId = new Guid("ba7c2575-1ff4-4d91-a9db-40c4e37eac96")
                        },
                        new
                        {
                            Id = new Guid("59e25a3a-157d-40a6-bed5-8149176337dd"),
                            Date = new DateTime(2024, 8, 4, 15, 31, 4, 531, DateTimeKind.Local).AddTicks(6034),
                            Description = "Write a review of the latest book read.",
                            MilestoneId = new Guid("cfe1c5c9-8fb7-45e1-b697-c22e8cdb26b0"),
                            TagId = new Guid("0be5e36f-4361-4655-95cf-19a7f1283daf"),
                            Title = "Write Book Review",
                            UserId = new Guid("914d5bdd-1c4c-4d74-b78e-9c26e06ff2e9")
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba7c2575-1ff4-4d91-a9db-40c4e37eac96"),
                            Email = "smarin@sample.com",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        },
                        new
                        {
                            Id = new Guid("914d5bdd-1c4c-4d74-b78e-9c26e06ff2e9"),
                            Email = "Gerald@sample.com",
                            FirstName = "Gerald",
                            LastName = "Vallejos",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME="
                        });
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblGoal_tblUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblGoal", "Goal")
                        .WithMany("tblMilestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMilestone_tblGoal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTask", b =>
                {
                    b.HasOne("AimHigh.PL.Entities.tblMilestone", "Milestone")
                        .WithMany("tblTasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblMilestone");

                    b.HasOne("AimHigh.PL.Entities.tblTag", "Tag")
                        .WithMany("tblTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AimHigh.PL.Entities.tblUser", "User")
                        .WithMany("tblTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTask_tblUser");

                    b.Navigation("Milestone");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblGoal", b =>
                {
                    b.Navigation("tblMilestones");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblMilestone", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblTag", b =>
                {
                    b.Navigation("tblTasks");
                });

            modelBuilder.Entity("AimHigh.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblGoals");

                    b.Navigation("tblTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
